// Generated by scripts/generate-content.mjs. Do not edit by hand.
export const contentIndex = {
  "featured": [
    {
      "slug": "order_processing_system",
      "title": "Order Management System",
      "eyebrow": "Commerce orchestration",
      "summary": "A commercial order aggregate with immutable price snapshots, explicit transitions, idempotent commands, and compensated inventory/payment coordination.",
      "focus": [
        "State machine",
        "Saga compensation",
        "Idempotency",
        "Optimistic concurrency"
      ],
      "invariants": [
        "An order is confirmed only after inventory and payment both succeed.",
        "Fulfilled quantity never exceeds confirmed, non-cancelled quantity.",
        "A retried command returns its original result without repeating side effects."
      ],
      "accent": "cobalt",
      "level": "Senior / Staff",
      "durationMinutes": 60,
      "variationCount": 5,
      "javaFileCount": 22,
      "pythonFileCount": 2,
      "fileCount": 24,
      "entryFile": "com/example/lld/order_processing_system/service/OrderService.java",
      "pythonEntryFile": "python/solution.py"
    },
    {
      "slug": "inventory_reservation_service",
      "title": "Inventory Reservation Service",
      "eyebrow": "Scarce-resource safety",
      "summary": "Atomic multi-SKU holds with confirm, release, expiry, deterministic allocation, and one-winner concurrency at the final unit.",
      "focus": [
        "Atomic allocation",
        "TTL expiry",
        "Lock ordering",
        "Injected clock"
      ],
      "invariants": [
        "Available stock is always on-hand minus reserved and never goes negative.",
        "A multi-line reservation commits every line or none of them.",
        "Confirm, release, and expiry consume a hold exactly once."
      ],
      "accent": "mint",
      "level": "Senior / Staff",
      "durationMinutes": 60,
      "variationCount": 9,
      "javaFileCount": 16,
      "pythonFileCount": 2,
      "fileCount": 18,
      "entryFile": "com/example/lld/inventory_reservation_service/service/InventoryReservationService.java",
      "pythonEntryFile": "python/solution.py"
    },
    {
      "slug": "coupon_promotion_engine",
      "title": "Coupon / Promotion Engine",
      "eyebrow": "Composable pricing policy",
      "summary": "Typed conditions and benefits for coupons, automatic campaigns, stacking, exclusivity, caps, preview, and atomic redemption limits.",
      "focus": [
        "Policy composition",
        "Exact money",
        "Deterministic stacking",
        "Usage limits"
      ],
      "invariants": [
        "Preview never consumes a redemption.",
        "Discounts cannot drive a line or order total below zero.",
        "Global and customer redemption counters move atomically."
      ],
      "accent": "amber",
      "level": "Senior / Staff",
      "durationMinutes": 60,
      "variationCount": 6,
      "javaFileCount": 18,
      "pythonFileCount": 2,
      "fileCount": 20,
      "entryFile": "src/main/java/com/example/lld/coupon_promotion_engine/PromotionEngine.java",
      "pythonEntryFile": "python/solution.py"
    },
    {
      "slug": "notification_framework",
      "title": "Notification Framework",
      "eyebrow": "Reliable multichannel delivery",
      "summary": "Versioned templates, locale fallback, recipient preferences, provider adapters, retries, deduplication, and an auditable delivery history.",
      "focus": [
        "Adapter ports",
        "Retry policy",
        "Dedupe",
        "Partial delivery"
      ],
      "invariants": [
        "Consent and quiet-hour rules are checked before provider delivery.",
        "Fallback attempts belong to one logical notification.",
        "Duplicate or stale callbacks cannot regress terminal state."
      ],
      "accent": "violet",
      "level": "Senior / Staff",
      "durationMinutes": 60,
      "variationCount": 7,
      "javaFileCount": 21,
      "pythonFileCount": 2,
      "fileCount": 23,
      "entryFile": "src/main/java/com/example/lld/notification_framework/NotificationService.java",
      "pythonEntryFile": "python/solution.py"
    },
    {
      "slug": "payment_processing_service",
      "title": "Payment Processing Service",
      "eyebrow": "Money and unknown outcomes",
      "summary": "Provider-neutral authorize, capture, void, and refund flows with partial amounts, callback reconciliation, and side-effect-safe retries.",
      "focus": [
        "Exact money",
        "Unknown outcomes",
        "Reconciliation",
        "Provider ports"
      ],
      "invariants": [
        "Captured total cannot exceed the authorization.",
        "Refunded total cannot exceed the captured total.",
        "A timeout remains unknown until the provider result is reconciled."
      ],
      "accent": "rose",
      "level": "Senior / Staff",
      "durationMinutes": 60,
      "variationCount": 6,
      "javaFileCount": 29,
      "pythonFileCount": 2,
      "fileCount": 31,
      "entryFile": "src/main/java/com/example/lld/payment_processing_service/service/PaymentService.java",
      "pythonEntryFile": "python/solution.py"
    },
    {
      "slug": "warehouse_fulfilment_domain",
      "title": "Warehouse Fulfilment Domain",
      "eyebrow": "Physical execution",
      "summary": "Split allocation, atomically claimed pick tasks, validated scans, short-pick recovery, packaging, shipping, and upstream status events.",
      "focus": [
        "Task claiming",
        "Scan idempotency",
        "Split fulfilment",
        "Exception recovery"
      ],
      "invariants": [
        "Picked, packed, and shipped quantities never exceed allocation.",
        "Only one worker can claim a pick task.",
        "A package contains only picked, previously unpacked quantities."
      ],
      "accent": "cyan",
      "level": "Senior / Staff",
      "durationMinutes": 60,
      "variationCount": 5,
      "javaFileCount": 27,
      "pythonFileCount": 2,
      "fileCount": 29,
      "entryFile": "com/example/lld/warehouse_fulfilment_domain/service/WarehouseFulfilmentService.java",
      "pythonEntryFile": "python/solution.py"
    },
    {
      "slug": "rate_limiter",
      "title": "Rate Limiter",
      "eyebrow": "Concurrent quota control",
      "summary": "Pluggable fixed-window and exact token-bucket policies with per-key isolation, weighted costs, live rules, and idle-state eviction.",
      "focus": [
        "Token bucket",
        "Fixed window",
        "Per-key locks",
        "Boundary semantics"
      ],
      "invariants": [
        "Concurrent callers cannot spend the final unit more than once.",
        "Rejected requests do not consume capacity.",
        "Unrelated keys do not serialize one another."
      ],
      "accent": "lime",
      "level": "Senior / Staff",
      "durationMinutes": 60,
      "variationCount": 4,
      "javaFileCount": 21,
      "pythonFileCount": 2,
      "fileCount": 23,
      "entryFile": "src/main/java/com/example/lld/rate_limiter/service/RateLimiter.java",
      "pythonEntryFile": "python/solution.py"
    },
    {
      "slug": "product_catalog_service",
      "title": "Product Catalog Service",
      "eyebrow": "Typed product truth",
      "summary": "Category schemas, validated attributes and variants, stable IDs and SKUs, optimistic versions, lifecycle control, and schema-impact reports.",
      "focus": [
        "Typed attributes",
        "SKU uniqueness",
        "Version history",
        "Schema evolution"
      ],
      "invariants": [
        "A product activates only when every required attribute is valid.",
        "Stable SKUs cannot be reused for another product.",
        "One of two stale concurrent updates fails with a version conflict."
      ],
      "accent": "orange",
      "level": "Senior / Staff",
      "durationMinutes": 60,
      "variationCount": 5,
      "javaFileCount": 50,
      "pythonFileCount": 2,
      "fileCount": 52,
      "entryFile": "com/example/lld/product_catalog_service/service/ProductCatalogService.java",
      "pythonEntryFile": "python/solution.py"
    }
  ],
  "catalog": [
    {
      "title": "E-Commerce Platform",
      "slug": "e_commerce",
      "summary": "umbrella checkout workflows and embedded examples.",
      "category": "Commerce, retail, and logistics",
      "javaFileCount": 20,
      "pythonFileCount": 0,
      "entryFile": "com/example/lld/e_commerce/com/mycompany/app/order_processing_system/OrderProcessingService.java",
      "pythonEntryFile": "com/example/lld/e_commerce/com/mycompany/app/Main.java"
    },
    {
      "title": "Online Bookstore",
      "slug": "online_bookstore",
      "summary": "catalog, patron, inventory, and order processing.",
      "category": "Commerce, retail, and logistics",
      "javaFileCount": 7,
      "pythonFileCount": 0,
      "entryFile": "com/example/lld/online_bookstore/InventoryManager.java",
      "pythonEntryFile": "com/example/lld/online_bookstore/Book.java"
    },
    {
      "title": "Product Catalog Service",
      "slug": "product_catalog_service",
      "summary": "authoritative product metadata and lifecycle.",
      "category": "Commerce, retail, and logistics",
      "javaFileCount": 50,
      "pythonFileCount": 2,
      "entryFile": "com/example/lld/product_catalog_service/service/ProductCatalogService.java",
      "pythonEntryFile": "python/solution.py"
    },
    {
      "title": "Product Search System",
      "slug": "product_search_system",
      "summary": "discovery, filters, sorting, and relevance.",
      "category": "Commerce, retail, and logistics",
      "javaFileCount": 3,
      "pythonFileCount": 0,
      "entryFile": "com/example/lld/product_search_system/service/SearchService.java",
      "pythonEntryFile": "com/example/lld/product_search_system/Main.java"
    },
    {
      "title": "Shopping Cart with Expiration",
      "slug": "shopping_cart_with_expiration",
      "summary": "cart lifecycle and time-based expiry.",
      "category": "Commerce, retail, and logistics",
      "javaFileCount": 3,
      "pythonFileCount": 0,
      "entryFile": "com/example/lld/shopping_cart_with_expiration/Main.java",
      "pythonEntryFile": "com/example/lld/shopping_cart_with_expiration/CartItem.java"
    },
    {
      "title": "Order Management System",
      "slug": "order_processing_system",
      "summary": "order lifecycle and downstream coordination.",
      "category": "Commerce, retail, and logistics",
      "javaFileCount": 22,
      "pythonFileCount": 2,
      "entryFile": "com/example/lld/order_processing_system/service/OrderService.java",
      "pythonEntryFile": "python/solution.py"
    },
    {
      "title": "Inventory Reservation Service",
      "slug": "inventory_reservation_service",
      "summary": "atomic stock holds, confirmation, release, and expiry.",
      "category": "Commerce, retail, and logistics",
      "javaFileCount": 16,
      "pythonFileCount": 2,
      "entryFile": "com/example/lld/inventory_reservation_service/service/InventoryReservationService.java",
      "pythonEntryFile": "python/solution.py"
    },
    {
      "title": "Coupon / Promotion Engine",
      "slug": "coupon_promotion_engine",
      "summary": "eligibility, stacking, discount calculation, and redemption.",
      "category": "Commerce, retail, and logistics",
      "javaFileCount": 18,
      "pythonFileCount": 2,
      "entryFile": "src/main/java/com/example/lld/coupon_promotion_engine/PromotionEngine.java",
      "pythonEntryFile": "python/solution.py"
    },
    {
      "title": "Payment Processing Service",
      "slug": "payment_processing_service",
      "summary": "authorize, capture, void, refund, and provider callbacks.",
      "category": "Commerce, retail, and logistics",
      "javaFileCount": 29,
      "pythonFileCount": 2,
      "entryFile": "src/main/java/com/example/lld/payment_processing_service/service/PaymentService.java",
      "pythonEntryFile": "python/solution.py"
    },
    {
      "title": "Warehouse Fulfilment Domain",
      "slug": "warehouse_fulfilment_domain",
      "summary": "allocate, pick, pack, and ship.",
      "category": "Commerce, retail, and logistics",
      "javaFileCount": 27,
      "pythonFileCount": 2,
      "entryFile": "com/example/lld/warehouse_fulfilment_domain/service/WarehouseFulfilmentService.java",
      "pythonEntryFile": "python/solution.py"
    },
    {
      "title": "Sales Analytics Dashboard",
      "slug": "sales_analytics_dashboard",
      "summary": "event aggregation and metrics.",
      "category": "Commerce, retail, and logistics",
      "javaFileCount": 2,
      "pythonFileCount": 0,
      "entryFile": "com/example/lld/sales_analytics_dashboard/Main.java",
      "pythonEntryFile": "com/example/lld/sales_analytics_dashboard/Main.java"
    },
    {
      "title": "Food Delivery Service",
      "slug": "food_delivery_service",
      "summary": "restaurant order and courier lifecycle.",
      "category": "Commerce, retail, and logistics",
      "javaFileCount": 0,
      "pythonFileCount": 0,
      "entryFile": "",
      "pythonEntryFile": ""
    },
    {
      "title": "Restaurant Management System",
      "slug": "restaurant_management_system",
      "summary": "reservations, tables, kitchen, and billing.",
      "category": "Commerce, retail, and logistics",
      "javaFileCount": 0,
      "pythonFileCount": 0,
      "entryFile": "",
      "pythonEntryFile": ""
    },
    {
      "title": "Property Listing / Property Hunt Service",
      "slug": "property_listing_service",
      "summary": "listings, typed measurements, search, shortlist, and sale lifecycle.",
      "category": "Commerce, retail, and logistics",
      "javaFileCount": 0,
      "pythonFileCount": 0,
      "entryFile": "",
      "pythonEntryFile": ""
    },
    {
      "title": "Package Locker Service",
      "slug": "package_locker",
      "summary": "size-aware compartment allocation, pickup codes, expiry, and release.",
      "category": "Commerce, retail, and logistics",
      "javaFileCount": 0,
      "pythonFileCount": 0,
      "entryFile": "",
      "pythonEntryFile": ""
    },
    {
      "title": "ATM System",
      "slug": "atm_system",
      "summary": "authentication, account operations, and cash dispensing.",
      "category": "Finance and trading",
      "javaFileCount": 12,
      "pythonFileCount": 0,
      "entryFile": "src/main/java/com/example/lld/atm_system/service/BankingService.java",
      "pythonEntryFile": "src/main/java/com/example/lld/atm_system/Main.java"
    },
    {
      "title": "Digital Wallet Service",
      "slug": "digital_wallet_service",
      "summary": "accounts, ledger entries, transfers, and funding methods.",
      "category": "Finance and trading",
      "javaFileCount": 0,
      "pythonFileCount": 0,
      "entryFile": "",
      "pythonEntryFile": ""
    },
    {
      "title": "Online Stock Exchange",
      "slug": "stock_exchange",
      "summary": "orders, matching, portfolios, and trade settlement.",
      "category": "Finance and trading",
      "javaFileCount": 29,
      "pythonFileCount": 0,
      "entryFile": "com/example/lld/stock_exchange/com/mycompany/app/Main.java",
      "pythonEntryFile": "com/example/lld/stock_exchange/com/mycompany/app/account/AccountStatus.java"
    },
    {
      "title": "Splitwise",
      "slug": "splitwise",
      "summary": "expense allocation, balances, and settlement.",
      "category": "Finance and trading",
      "javaFileCount": 0,
      "pythonFileCount": 0,
      "entryFile": "",
      "pythonEntryFile": ""
    },
    {
      "title": "Loan Ledger / EMI Management Service",
      "slug": "loan_ledger_service",
      "summary": "schedules, immutable ledger entries, payments, and balances.",
      "category": "Finance and trading",
      "javaFileCount": 0,
      "pythonFileCount": 0,
      "entryFile": "",
      "pythonEntryFile": ""
    },
    {
      "title": "Airline Management System",
      "slug": "airline_management_system",
      "summary": "flights, seats, passengers, and booking.",
      "category": "Booking, facilities, and education",
      "javaFileCount": 0,
      "pythonFileCount": 0,
      "entryFile": "",
      "pythonEntryFile": ""
    },
    {
      "title": "Ticket Booking / Ticket Master",
      "slug": "ticket_master",
      "summary": "movie or concert inventory, seat holds, and booking.",
      "category": "Booking, facilities, and education",
      "javaFileCount": 20,
      "pythonFileCount": 0,
      "entryFile": "com/example/lld/ticket_master/com/mycompany/app/controller/BookingController.java",
      "pythonEntryFile": "com/example/lld/ticket_master/com/mycompany/app/controller/BookingController.java"
    },
    {
      "title": "Car Rental System",
      "slug": "car_rental_system",
      "summary": "vehicles, availability, reservations, and payment.",
      "category": "Booking, facilities, and education",
      "javaFileCount": 0,
      "pythonFileCount": 0,
      "entryFile": "",
      "pythonEntryFile": ""
    },
    {
      "title": "Hotel Management System",
      "slug": "hotel_management",
      "summary": "rooms, stays, services, and billing.",
      "category": "Booking, facilities, and education",
      "javaFileCount": 0,
      "pythonFileCount": 0,
      "entryFile": "",
      "pythonEntryFile": ""
    },
    {
      "title": "Library Management System",
      "slug": "library_management_system",
      "summary": "catalog, members, loans, and fines.",
      "category": "Booking, facilities, and education",
      "javaFileCount": 5,
      "pythonFileCount": 0,
      "entryFile": "com/example/lld/library_management_system/Main.java",
      "pythonEntryFile": "com/example/lld/library_management_system/Book.java"
    },
    {
      "title": "Course Registration System",
      "slug": "course_registration_system",
      "summary": "sections, prerequisites, capacity, and waitlists.",
      "category": "Booking, facilities, and education",
      "javaFileCount": 0,
      "pythonFileCount": 0,
      "entryFile": "",
      "pythonEntryFile": ""
    },
    {
      "title": "Online Learning Platform",
      "slug": "online_learning_platform",
      "summary": "courses, enrollment, progress, and assessment.",
      "category": "Booking, facilities, and education",
      "javaFileCount": 0,
      "pythonFileCount": 0,
      "entryFile": "",
      "pythonEntryFile": ""
    },
    {
      "title": "Parking Lot",
      "slug": "parking_lot",
      "summary": "allocation, tickets, availability, and pricing.",
      "category": "Booking, facilities, and education",
      "javaFileCount": 11,
      "pythonFileCount": 0,
      "entryFile": "com/example/lld/parking_lot/ParkingLotService.java",
      "pythonEntryFile": "com/example/lld/parking_lot/commands/CommandExecutor.java"
    },
    {
      "title": "Elevator System",
      "slug": "elevator_system",
      "summary": "requests, dispatch, movement, and door state.",
      "category": "Booking, facilities, and education",
      "javaFileCount": 8,
      "pythonFileCount": 0,
      "entryFile": "com/example/lld/elevator_system/ElevatorController.java",
      "pythonEntryFile": "com/example/lld/elevator_system/Direction.java"
    },
    {
      "title": "Event Calendar / Meeting Scheduler",
      "slug": "event_calendar",
      "summary": "invitations, free slots, room allocation, and versioned changes.",
      "category": "Booking, facilities, and education",
      "javaFileCount": 0,
      "pythonFileCount": 0,
      "entryFile": "",
      "pythonEntryFile": ""
    },
    {
      "title": "Online Coding Contest Platform",
      "slug": "online_coding_contest_platform",
      "summary": "contests, submissions, judging, scoring, and leaderboards.",
      "category": "Booking, facilities, and education",
      "javaFileCount": 0,
      "pythonFileCount": 0,
      "entryFile": "",
      "pythonEntryFile": ""
    },
    {
      "title": "Hospital Appointment System",
      "slug": "hospital_appointment_system",
      "summary": "doctor schedules, slot holds, bookings, and cancellation.",
      "category": "Booking, facilities, and education",
      "javaFileCount": 0,
      "pythonFileCount": 0,
      "entryFile": "",
      "pythonEntryFile": ""
    },
    {
      "title": "Online Assessment Platform",
      "slug": "online_assessment_platform",
      "summary": "versioned tests, autosave/resume, scoring, and ranked cohorts.",
      "category": "Booking, facilities, and education",
      "javaFileCount": 0,
      "pythonFileCount": 0,
      "entryFile": "",
      "pythonEntryFile": ""
    },
    {
      "title": "Cache",
      "slug": "cache",
      "summary": "bounded storage and eviction policies.",
      "category": "Infrastructure and reusable components",
      "javaFileCount": 26,
      "pythonFileCount": 0,
      "entryFile": "com/example/lld/cache/code/Main.java",
      "pythonEntryFile": "com/example/lld/cache/CacheFactory.java"
    },
    {
      "title": "Multi-Level Cache",
      "slug": "multi_level_cache",
      "summary": "coordinated cache tiers and usage metrics.",
      "category": "Infrastructure and reusable components",
      "javaFileCount": 21,
      "pythonFileCount": 0,
      "entryFile": "com/example/lld/multi_level_cache/code/MultiLevelCacheService.java",
      "pythonEntryFile": "com/example/lld/multi_level_cache/code/algorithms/DoublyLinkedList.java"
    },
    {
      "title": "Custom Hash Map",
      "slug": "custom_hash_map",
      "summary": "buckets, collisions, resize, and map semantics.",
      "category": "Infrastructure and reusable components",
      "javaFileCount": 2,
      "pythonFileCount": 0,
      "entryFile": "com/example/lld/custom_hash_map/Main.java",
      "pythonEntryFile": "com/example/lld/custom_hash_map/CustomHashMap.java"
    },
    {
      "title": "Rate Limiter",
      "slug": "rate_limiter",
      "summary": "keys, policies, decisions, and concurrent quota updates.",
      "category": "Infrastructure and reusable components",
      "javaFileCount": 21,
      "pythonFileCount": 2,
      "entryFile": "src/main/java/com/example/lld/rate_limiter/service/RateLimiter.java",
      "pythonEntryFile": "python/solution.py"
    },
    {
      "title": "Publish-Subscribe System",
      "slug": "pub_sub_system",
      "summary": "topics, publishers, subscribers, and delivery.",
      "category": "Infrastructure and reusable components",
      "javaFileCount": 0,
      "pythonFileCount": 0,
      "entryFile": "",
      "pythonEntryFile": ""
    },
    {
      "title": "Notification Framework",
      "slug": "notification_framework",
      "summary": "templates, preferences, channels, retries, and status.",
      "category": "Infrastructure and reusable components",
      "javaFileCount": 21,
      "pythonFileCount": 2,
      "entryFile": "src/main/java/com/example/lld/notification_framework/NotificationService.java",
      "pythonEntryFile": "python/solution.py"
    },
    {
      "title": "Logging",
      "slug": "logging",
      "summary": "log levels, processors, appenders, and extensibility.",
      "category": "Infrastructure and reusable components",
      "javaFileCount": 11,
      "pythonFileCount": 0,
      "entryFile": "framework/com/example/lld/logging_framework/Main.java",
      "pythonEntryFile": "framework/com/example/lld/logging_framework/Logger.java"
    },
    {
      "title": "File System",
      "slug": "file_system",
      "summary": "files, directories, traversal, and operations.",
      "category": "Infrastructure and reusable components",
      "javaFileCount": 1,
      "pythonFileCount": 0,
      "entryFile": "com/example/lld/file_system/com/mycompany/app/Main.java",
      "pythonEntryFile": "com/example/lld/file_system/com/mycompany/app/Main.java"
    },
    {
      "title": "JSON Parser",
      "slug": "json_parser",
      "summary": "tokenization, typed values, parsing, and serialization.",
      "category": "Infrastructure and reusable components",
      "javaFileCount": 0,
      "pythonFileCount": 0,
      "entryFile": "",
      "pythonEntryFile": ""
    },
    {
      "title": "In-Memory Relational Database",
      "slug": "in_memory_relational_database",
      "summary": "schemas, rows, indexes, queries, and transactions.",
      "category": "Infrastructure and reusable components",
      "javaFileCount": 0,
      "pythonFileCount": 0,
      "entryFile": "",
      "pythonEntryFile": ""
    },
    {
      "title": "Extensible Calculator",
      "slug": "calculator",
      "summary": "operation strategies, parsing boundaries, history, and undo decisions.",
      "category": "Infrastructure and reusable components",
      "javaFileCount": 0,
      "pythonFileCount": 0,
      "entryFile": "",
      "pythonEntryFile": ""
    },
    {
      "title": "Job / Task Scheduler",
      "slug": "job_scheduler",
      "summary": "timed work, bounded execution, retries, and graceful shutdown.",
      "category": "Infrastructure and reusable components",
      "javaFileCount": 0,
      "pythonFileCount": 0,
      "entryFile": "",
      "pythonEntryFile": ""
    },
    {
      "title": "Hit Counter",
      "slug": "hit_counter",
      "summary": "rolling windows, bucket boundaries, concurrent increments, and eviction.",
      "category": "Infrastructure and reusable components",
      "javaFileCount": 0,
      "pythonFileCount": 0,
      "entryFile": "",
      "pythonEntryFile": ""
    },
    {
      "title": "Generic Rule Engine / Rule Matcher",
      "slug": "rule_engine",
      "summary": "typed facts, composable conditions, explanations, and actions.",
      "category": "Infrastructure and reusable components",
      "javaFileCount": 0,
      "pythonFileCount": 0,
      "entryFile": "",
      "pythonEntryFile": ""
    },
    {
      "title": "Custom Thread Pool Executor",
      "slug": "thread_pool_executor",
      "summary": "bounded queues, workers, futures, rejection, and lifecycle.",
      "category": "Infrastructure and reusable components",
      "javaFileCount": 0,
      "pythonFileCount": 0,
      "entryFile": "",
      "pythonEntryFile": ""
    },
    {
      "title": "Authentication and Authorization Service",
      "slug": "authentication_authorization_service",
      "summary": "challenges, OTP/OAuth, sessions, revocation, and policy.",
      "category": "Infrastructure and reusable components",
      "javaFileCount": 0,
      "pythonFileCount": 0,
      "entryFile": "",
      "pythonEntryFile": ""
    },
    {
      "title": "Webhook Dispatcher",
      "slug": "webhook_dispatcher",
      "summary": "subscriptions, signed delivery, retry schedules, dedupe, and dead letters.",
      "category": "Infrastructure and reusable components",
      "javaFileCount": 0,
      "pythonFileCount": 0,
      "entryFile": "",
      "pythonEntryFile": ""
    },
    {
      "title": "Distributed ID Generator",
      "slug": "distributed_id_generator",
      "summary": "uniqueness, ordering, clock safety, and node coordination.",
      "category": "Infrastructure and reusable components",
      "javaFileCount": 0,
      "pythonFileCount": 0,
      "entryFile": "",
      "pythonEntryFile": ""
    },
    {
      "title": "Key-Value Store with Indexes",
      "slug": "key_value_store",
      "summary": "typed records, secondary indexes, atomic writes, and recovery.",
      "category": "Infrastructure and reusable components",
      "javaFileCount": 0,
      "pythonFileCount": 0,
      "entryFile": "",
      "pythonEntryFile": ""
    },
    {
      "title": "Coordination Service",
      "slug": "coordination_service",
      "summary": "sessions, leases, watches, ephemeral nodes, and fencing tokens.",
      "category": "Infrastructure and reusable components",
      "javaFileCount": 0,
      "pythonFileCount": 0,
      "entryFile": "",
      "pythonEntryFile": ""
    },
    {
      "title": "Monitoring and Alerting Platform",
      "slug": "monitoring_alerting_platform",
      "summary": "metric ingestion, rules, incidents, silences, and notification.",
      "category": "Infrastructure and reusable components",
      "javaFileCount": 0,
      "pythonFileCount": 0,
      "entryFile": "",
      "pythonEntryFile": ""
    },
    {
      "title": "Configuration Management Service",
      "slug": "configuration_management_service",
      "summary": "versioned configuration, subscriptions, rollout, and rollback.",
      "category": "Infrastructure and reusable components",
      "javaFileCount": 0,
      "pythonFileCount": 0,
      "entryFile": "",
      "pythonEntryFile": ""
    },
    {
      "title": "Resumable Upload Service",
      "slug": "resumable_upload_service",
      "summary": "chunk sessions, integrity, retry, completion, and cleanup.",
      "category": "Infrastructure and reusable components",
      "javaFileCount": 0,
      "pythonFileCount": 0,
      "entryFile": "",
      "pythonEntryFile": ""
    },
    {
      "title": "T9 Dictionary",
      "slug": "t9_dictionary",
      "summary": "keypad encoding, prefix lookup, ranking, and dictionary updates.",
      "category": "Infrastructure and reusable components",
      "javaFileCount": 0,
      "pythonFileCount": 0,
      "entryFile": "",
      "pythonEntryFile": ""
    },
    {
      "title": "URL Shortener",
      "slug": "url_shortener",
      "summary": "key generation, redirects, aliases, expiry, and analytics boundaries.",
      "category": "Infrastructure and reusable components",
      "javaFileCount": 0,
      "pythonFileCount": 0,
      "entryFile": "",
      "pythonEntryFile": ""
    },
    {
      "title": "CSV Object Mapper",
      "slug": "csv_object_mapper",
      "summary": "schema/annotation binding, typed conversion, diagnostics, and streaming.",
      "category": "Infrastructure and reusable components",
      "javaFileCount": 0,
      "pythonFileCount": 0,
      "entryFile": "",
      "pythonEntryFile": ""
    },
    {
      "title": "Binary Tree Validator",
      "slug": "binary_tree_validator",
      "summary": "edge validation, parent constraints, cycles, roots, and diagnostics.",
      "category": "Infrastructure and reusable components",
      "javaFileCount": 0,
      "pythonFileCount": 0,
      "entryFile": "",
      "pythonEntryFile": ""
    },
    {
      "title": "Social Network",
      "slug": "social_network",
      "summary": "profiles, friendship, posts, feeds, messaging, and privacy.",
      "category": "Social, collaboration, and content",
      "javaFileCount": 4,
      "pythonFileCount": 0,
      "entryFile": "com/example/lld/social_network/Main.java",
      "pythonEntryFile": "com/example/lld/social_network/Main.java"
    },
    {
      "title": "Professional Network / LinkedIn",
      "slug": "linkedin",
      "summary": "career profiles, connections, jobs, and applications.",
      "category": "Social, collaboration, and content",
      "javaFileCount": 0,
      "pythonFileCount": 0,
      "entryFile": "",
      "pythonEntryFile": ""
    },
    {
      "title": "Stack Overflow",
      "slug": "stack_overflow",
      "summary": "questions, answers, votes, tags, and reputation.",
      "category": "Social, collaboration, and content",
      "javaFileCount": 0,
      "pythonFileCount": 0,
      "entryFile": "",
      "pythonEntryFile": ""
    },
    {
      "title": "Task Management",
      "slug": "task_management",
      "summary": "task ownership, status, priority, reminders, and history.",
      "category": "Social, collaboration, and content",
      "javaFileCount": 0,
      "pythonFileCount": 0,
      "entryFile": "",
      "pythonEntryFile": ""
    },
    {
      "title": "Music Streaming Service",
      "slug": "music_streaming_service",
      "summary": "catalog, playlists, library, and playback sessions.",
      "category": "Social, collaboration, and content",
      "javaFileCount": 0,
      "pythonFileCount": 0,
      "entryFile": "",
      "pythonEntryFile": ""
    },
    {
      "title": "Cricket Information System",
      "slug": "cricinfo",
      "summary": "fixtures, delivery events, live scores, and scorecards.",
      "category": "Social, collaboration, and content",
      "javaFileCount": 0,
      "pythonFileCount": 0,
      "entryFile": "",
      "pythonEntryFile": ""
    },
    {
      "title": "Online Auction System",
      "slug": "online_auction_system",
      "summary": "listings, bids, proxy rules, and closure.",
      "category": "Social, collaboration, and content",
      "javaFileCount": 0,
      "pythonFileCount": 0,
      "entryFile": "",
      "pythonEntryFile": ""
    },
    {
      "title": "Online Book Reader",
      "slug": "online_book_reader",
      "summary": "entitlements, reading sessions, progress, bookmarks, and offline merge.",
      "category": "Social, collaboration, and content",
      "javaFileCount": 0,
      "pythonFileCount": 0,
      "entryFile": "",
      "pythonEntryFile": ""
    },
    {
      "title": "Text Editor",
      "slug": "text_editor",
      "summary": "edit commands, ranges, clipboard, history, undo, and redo.",
      "category": "Social, collaboration, and content",
      "javaFileCount": 0,
      "pythonFileCount": 0,
      "entryFile": "",
      "pythonEntryFile": ""
    },
    {
      "title": "Survey and Form Builder",
      "slug": "survey_form_builder",
      "summary": "versioned forms, branching, responses, validation, and publication.",
      "category": "Social, collaboration, and content",
      "javaFileCount": 0,
      "pythonFileCount": 0,
      "entryFile": "",
      "pythonEntryFile": ""
    },
    {
      "title": "Chat and Messaging Service",
      "slug": "chat_messaging_service",
      "summary": "conversations, delivery, ordering, receipts, and reconnect.",
      "category": "Social, collaboration, and content",
      "javaFileCount": 0,
      "pythonFileCount": 0,
      "entryFile": "",
      "pythonEntryFile": ""
    },
    {
      "title": "Document Collaboration Platform",
      "slug": "document_collaboration_platform",
      "summary": "access control, operations, revisions, presence, and convergence.",
      "category": "Social, collaboration, and content",
      "javaFileCount": 0,
      "pythonFileCount": 0,
      "entryFile": "",
      "pythonEntryFile": ""
    },
    {
      "title": "Caller Identification Service",
      "slug": "caller_identification_service",
      "summary": "contacts, normalized numbers, tags, privacy, and spam reputation.",
      "category": "Social, collaboration, and content",
      "javaFileCount": 0,
      "pythonFileCount": 0,
      "entryFile": "",
      "pythonEntryFile": ""
    },
    {
      "title": "Cab Booking / Ride Sharing",
      "slug": "cab_booking_service",
      "summary": "riders, drivers, matching, trips, and fares.",
      "category": "Mobility, games, machines, and civic systems",
      "javaFileCount": 18,
      "pythonFileCount": 0,
      "entryFile": "com/example/lld/cab_booking_service/code/contollers/CabsController.java",
      "pythonEntryFile": "com/example/lld/cab_booking_service/code/contollers/CabsController.java"
    },
    {
      "title": "Chess",
      "slug": "chess_game",
      "summary": "legal moves, king safety, history, and game outcomes.",
      "category": "Mobility, games, machines, and civic systems",
      "javaFileCount": 0,
      "pythonFileCount": 0,
      "entryFile": "",
      "pythonEntryFile": ""
    },
    {
      "title": "Snake and Ladder",
      "slug": "snake_ladder",
      "summary": "board transitions, turn rotation, and game sessions.",
      "category": "Mobility, games, machines, and civic systems",
      "javaFileCount": 1,
      "pythonFileCount": 0,
      "entryFile": "src/main/java/com/example/lld/snake_ladder/SnakeAndLadderGame.java",
      "pythonEntryFile": "src/main/java/com/example/lld/snake_ladder/SnakeAndLadderGame.java"
    },
    {
      "title": "Tic-Tac-Toe",
      "slug": "tic_tac_toe",
      "summary": "board, turns, legal moves, winner, and draw.",
      "category": "Mobility, games, machines, and civic systems",
      "javaFileCount": 5,
      "pythonFileCount": 0,
      "entryFile": "com/example/lld/tic_tac_toe/Main.java",
      "pythonEntryFile": "com/example/lld/tic_tac_toe/Board.java"
    },
    {
      "title": "Vending Machine",
      "slug": "vending_machine",
      "summary": "selection, inventory, payment, dispensing, and configurable coffee recipes.",
      "category": "Mobility, games, machines, and civic systems",
      "javaFileCount": 9,
      "pythonFileCount": 0,
      "entryFile": "com/example/lld/vending_machine/Main.java",
      "pythonEntryFile": "com/example/lld/vending_machine/IdleState.java"
    },
    {
      "title": "Traffic Signal Control",
      "slug": "traffic_signal",
      "summary": "signal cycles, intersections, and emergency priority.",
      "category": "Mobility, games, machines, and civic systems",
      "javaFileCount": 1,
      "pythonFileCount": 0,
      "entryFile": "com/example/lld/traffic_signal/TrafficSignal.java",
      "pythonEntryFile": "com/example/lld/traffic_signal/TrafficSignal.java"
    },
    {
      "title": "Voting System",
      "slug": "voting_system",
      "summary": "eligibility, secret ballots, duplicate prevention, and tallying.",
      "category": "Mobility, games, machines, and civic systems",
      "javaFileCount": 0,
      "pythonFileCount": 0,
      "entryFile": "",
      "pythonEntryFile": ""
    },
    {
      "title": "Bowling Alley",
      "slug": "bowling_alley",
      "summary": "frames, legal rolls, strike/spare bonuses, lanes, and scorecards.",
      "category": "Mobility, games, machines, and civic systems",
      "javaFileCount": 0,
      "pythonFileCount": 0,
      "entryFile": "",
      "pythonEntryFile": ""
    },
    {
      "title": "Blackjack",
      "slug": "blackjack",
      "summary": "deck/shoe, hands, dealer policy, wagers, outcomes, and settlement.",
      "category": "Mobility, games, machines, and civic systems",
      "javaFileCount": 0,
      "pythonFileCount": 0,
      "entryFile": "",
      "pythonEntryFile": ""
    },
    {
      "title": "Deck of Cards",
      "slug": "deck_of_cards",
      "summary": "card identity, deck composition, shuffle, deal, and reusable game policies.",
      "category": "Mobility, games, machines, and civic systems",
      "javaFileCount": 0,
      "pythonFileCount": 0,
      "entryFile": "",
      "pythonEntryFile": ""
    },
    {
      "title": "Othello / Reversi",
      "slug": "othello",
      "summary": "legal directional captures, turns, pass rules, scoring, and two model variations.",
      "category": "Mobility, games, machines, and civic systems",
      "javaFileCount": 0,
      "pythonFileCount": 0,
      "entryFile": "",
      "pythonEntryFile": ""
    },
    {
      "title": "Battleship",
      "slug": "battleship",
      "summary": "fleet placement, hidden boards, attacks, hit state, and winner detection.",
      "category": "Mobility, games, machines, and civic systems",
      "javaFileCount": 0,
      "pythonFileCount": 0,
      "entryFile": "",
      "pythonEntryFile": ""
    },
    {
      "title": "Connect Four",
      "slug": "connect_four",
      "summary": "column gravity, turns, win detection, draw state, and alternate boards.",
      "category": "Mobility, games, machines, and civic systems",
      "javaFileCount": 0,
      "pythonFileCount": 0,
      "entryFile": "",
      "pythonEntryFile": ""
    },
    {
      "title": "Snake Video Game",
      "slug": "snake_video_game",
      "summary": "movement ticks, growth, collisions, food policy, and game loop.",
      "category": "Mobility, games, machines, and civic systems",
      "javaFileCount": 0,
      "pythonFileCount": 0,
      "entryFile": "",
      "pythonEntryFile": ""
    },
    {
      "title": "Smart Home",
      "slug": "smart_home",
      "summary": "devices, commands, schedules, state, usage, and automation rules.",
      "category": "Mobility, games, machines, and civic systems",
      "javaFileCount": 0,
      "pythonFileCount": 0,
      "entryFile": "",
      "pythonEntryFile": ""
    },
    {
      "title": "Jukebox",
      "slug": "jukebox",
      "summary": "credits, selection queue, playback state, and device adapters.",
      "category": "Mobility, games, machines, and civic systems",
      "javaFileCount": 0,
      "pythonFileCount": 0,
      "entryFile": "",
      "pythonEntryFile": ""
    },
    {
      "title": "Maps Navigation Service",
      "slug": "maps_navigation_service",
      "summary": "route alternatives, travel modes, guidance, and rerouting alerts.",
      "category": "Mobility, games, machines, and civic systems",
      "javaFileCount": 0,
      "pythonFileCount": 0,
      "entryFile": "",
      "pythonEntryFile": ""
    },
    {
      "title": "Robotic Vacuum Cleaner",
      "slug": "robotic_vacuum_cleaner",
      "summary": "map/grid state, movement policy, cleaning commands, and recovery.",
      "category": "Mobility, games, machines, and civic systems",
      "javaFileCount": 0,
      "pythonFileCount": 0,
      "entryFile": "",
      "pythonEntryFile": ""
    },
    {
      "title": "Pandemic Tracker",
      "slug": "pandemic_tracker",
      "summary": "disease cases, regional aggregates, outcomes, and trend reporting.",
      "category": "Mobility, games, machines, and civic systems",
      "javaFileCount": 0,
      "pythonFileCount": 0,
      "entryFile": "",
      "pythonEntryFile": ""
    }
  ],
  "principles": [
    {
      "title": "Single Responsibility Principle",
      "slug": "single_responsibility",
      "summary": "Does this unit have one coherent reason to change?",
      "group": "SOLID",
      "javaFileCount": 1,
      "entryFile": "InvoiceDemo.java"
    },
    {
      "title": "Open/Closed Principle",
      "slug": "open_closed",
      "summary": "Can expected variants be added without editing stable policy?",
      "group": "SOLID",
      "javaFileCount": 2,
      "entryFile": "AreaCalculator.java"
    },
    {
      "title": "Liskov Substitution Principle",
      "slug": "liskov_substitution",
      "summary": "Can every subtype honor the observable contract of its base type?",
      "group": "SOLID",
      "javaFileCount": 2,
      "entryFile": "AreaCalculator.java"
    },
    {
      "title": "Interface Segregation Principle",
      "slug": "interface_segregation",
      "summary": "Does each client depend only on operations it needs?",
      "group": "SOLID",
      "javaFileCount": 2,
      "entryFile": "WorkerDemo.java"
    },
    {
      "title": "Dependency Inversion Principle",
      "slug": "dependency_inversion",
      "summary": "Does policy depend on abstractions rather than infrastructure details?",
      "group": "SOLID",
      "javaFileCount": 2,
      "entryFile": "DatabaseDemo.java"
    },
    {
      "title": "DRY, KISS, YAGNI & Law of Demeter",
      "slug": "complementary_principles",
      "summary": "Complementary heuristics for duplication, simplicity, scope control, and object collaboration.",
      "group": "Complementary",
      "javaFileCount": 0,
      "entryFile": ""
    }
  ],
  "patterns": [
    {
      "title": "Abstract Factory",
      "slug": "creational_abstract_factory",
      "summary": "Create compatible families of related objects.",
      "group": "Creational",
      "javaFileCount": 10,
      "entryFile": "AbstractFactoryDemo.java"
    },
    {
      "title": "Builder",
      "slug": "creational_builder",
      "summary": "Assemble a complex object step by step.",
      "group": "Creational",
      "javaFileCount": 1,
      "entryFile": "BuilderDemo.java"
    },
    {
      "title": "Factory",
      "slug": "creational_factory",
      "summary": "Centralize or defer the choice of concrete product.",
      "group": "Creational",
      "javaFileCount": 5,
      "entryFile": "FactoryMethodDemo.java"
    },
    {
      "title": "Prototype",
      "slug": "creational_prototype",
      "summary": "Create objects by copying configured prototypes.",
      "group": "Creational",
      "javaFileCount": 1,
      "entryFile": "PrototypeDemo.java"
    },
    {
      "title": "Singleton",
      "slug": "creational_singleton",
      "summary": "Provide one controlled instance of a class.",
      "group": "Creational",
      "javaFileCount": 3,
      "entryFile": "SingletonDemo.java"
    },
    {
      "title": "Adapter",
      "slug": "structural_adaptor",
      "summary": "Translate one interface into another expected by a client.",
      "group": "Structural",
      "javaFileCount": 1,
      "entryFile": "AdapterDemo.java"
    },
    {
      "title": "Bridge",
      "slug": "structural_bridge",
      "summary": "Vary an abstraction and its implementation independently.",
      "group": "Structural",
      "javaFileCount": 7,
      "entryFile": "BridgeDemo.java"
    },
    {
      "title": "Composite",
      "slug": "structural_composite",
      "summary": "Treat individual objects and object trees uniformly.",
      "group": "Structural",
      "javaFileCount": 1,
      "entryFile": "CompositeDemo.java"
    },
    {
      "title": "Decorator",
      "slug": "structural_decorator",
      "summary": "Add responsibilities to an object through composition.",
      "group": "Structural",
      "javaFileCount": 8,
      "entryFile": "pizzaExample/good/Main.java"
    },
    {
      "title": "Facade",
      "slug": "structural_facade",
      "summary": "Expose a simpler entry point to a complex subsystem.",
      "group": "Structural",
      "javaFileCount": 1,
      "entryFile": "FacadeDemo.java"
    },
    {
      "title": "Flyweight",
      "slug": "structural_flyweight",
      "summary": "Share reusable intrinsic state across many logical objects.",
      "group": "Structural",
      "javaFileCount": 12,
      "entryFile": "Game/good/Main.java"
    },
    {
      "title": "Proxy",
      "slug": "structural_proxy",
      "summary": "Control access to another object through the same interface.",
      "group": "Structural",
      "javaFileCount": 5,
      "entryFile": "Demo.java"
    },
    {
      "title": "Chain of Responsibility",
      "slug": "behavioral_chain_of_responsibilty",
      "summary": "Offer a request to an ordered sequence of handlers.",
      "group": "Behavioral",
      "javaFileCount": 1,
      "entryFile": "ChainOfResponsibilityDemo.java"
    },
    {
      "title": "Command",
      "slug": "behavioral_command",
      "summary": "Represent an operation as an object.",
      "group": "Behavioral",
      "javaFileCount": 1,
      "entryFile": "CommandDemo.java"
    },
    {
      "title": "Interpreter",
      "slug": "behavioral_interpretor",
      "summary": "Evaluate sentences in a small language or grammar.",
      "group": "Behavioral",
      "javaFileCount": 1,
      "entryFile": "InterpreterDemo.java"
    },
    {
      "title": "Iterator",
      "slug": "behavioral_iterator",
      "summary": "Traverse a collection without exposing its representation.",
      "group": "Behavioral",
      "javaFileCount": 1,
      "entryFile": "IteratorDemo.java"
    },
    {
      "title": "Mediator",
      "slug": "behavioral_mediator",
      "summary": "Centralize interactions among collaborating objects.",
      "group": "Behavioral",
      "javaFileCount": 5,
      "entryFile": "OnlineAuctionSystem/Main.java"
    },
    {
      "title": "Memento",
      "slug": "behavioral_momento",
      "summary": "Capture and restore an object's state without exposing internals.",
      "group": "Behavioral",
      "javaFileCount": 4,
      "entryFile": "Demo.java"
    },
    {
      "title": "Observer",
      "slug": "behavioral_observer",
      "summary": "Notify dependents when a subject changes.",
      "group": "Behavioral",
      "javaFileCount": 6,
      "entryFile": "IphoneExample/good/Main.java"
    },
    {
      "title": "State",
      "slug": "behavioral_state",
      "summary": "Change an object's behavior when its state changes.",
      "group": "Behavioral",
      "javaFileCount": 1,
      "entryFile": "StateDemo.java"
    },
    {
      "title": "Strategy",
      "slug": "behavioral_strategy",
      "summary": "Select an interchangeable algorithm at runtime.",
      "group": "Behavioral",
      "javaFileCount": 12,
      "entryFile": "vehicleExample/good/Main.java"
    },
    {
      "title": "Template Method",
      "slug": "behavioral_template_method",
      "summary": "Fix an algorithm's outline while allowing selected steps to vary.",
      "group": "Behavioral",
      "javaFileCount": 2,
      "entryFile": "PaymentDemo.java"
    },
    {
      "title": "Visitor",
      "slug": "behavioral_visitor",
      "summary": "Add operations to a stable object structure.",
      "group": "Behavioral",
      "javaFileCount": 11,
      "entryFile": "good/Main.java"
    }
  ],
  "lessons": [
    {
      "title": "60-Minute Senior/Staff LLD Interview",
      "slug": "senior_staff_lld_interview",
      "summary": "A timed answer method with clarifying questions, invariants, APIs, SOLID and pattern reasoning, one-hour Python scope, concurrency, follow-ups, and scoring.",
      "group": "Interview preparation",
      "javaFileCount": 0,
      "entryFile": ""
    },
    {
      "title": "Object-Oriented Programming",
      "slug": "object_oriented_programming",
      "summary": "Objects, encapsulation, abstraction, inheritance, polymorphism, and composition in interview designs.",
      "group": "Foundations",
      "javaFileCount": 0,
      "entryFile": ""
    },
    {
      "title": "Class Relationships",
      "slug": "class_relationships",
      "summary": "Association, aggregation, composition, dependency, inheritance, and how to choose between them.",
      "group": "Foundations",
      "javaFileCount": 0,
      "entryFile": ""
    },
    {
      "title": "Clean Code for LLD",
      "slug": "clean_code",
      "summary": "Names, boundaries, cohesion, error handling, and keeping an interview solution readable under change.",
      "group": "Foundations",
      "javaFileCount": 0,
      "entryFile": ""
    },
    {
      "title": "Testing Low-Level Designs",
      "slug": "testing_lld",
      "summary": "Test invariants, state transitions, failure paths, time, concurrency, and external ports deterministically.",
      "group": "Foundations",
      "javaFileCount": 0,
      "entryFile": ""
    },
    {
      "title": "Concurrency Fundamentals",
      "slug": "concurrency_fundamentals",
      "summary": "Memory visibility, atomicity, coordination primitives, lock design, and runnable Java exercises.",
      "group": "Concurrency",
      "javaFileCount": 13,
      "entryFile": "example/lld/concurrency/code/Main.java"
    },
    {
      "title": "Java Multithreading & Concurrency for LLD Interviews",
      "slug": "java_concurrency_lld_interviews",
      "summary": "ExecutorService, bounded BlockingQueue backpressure, semaphores, synchronization, failure handling, deterministic tests, and Senior/Staff trade-offs.",
      "group": "Concurrency",
      "javaFileCount": 1,
      "entryFile": "src/com/example/lld/concurrency/interview/ConcurrencyInterviewLab.java"
    },
    {
      "title": "Multithreading Introduction",
      "slug": "multithreading_introduction",
      "summary": "Threads, scheduling, shared state, race conditions, and the vocabulary needed for LLD interviews.",
      "group": "Concurrency",
      "javaFileCount": 0,
      "entryFile": ""
    },
    {
      "title": "Concurrency Question Bank",
      "slug": "concurrency_questions",
      "summary": "Practice prompts for producer-consumer, coordination, safety, liveness, and bounded-resource designs.",
      "group": "Concurrency",
      "javaFileCount": 0,
      "entryFile": ""
    },
    {
      "title": "UML for Low-Level Design",
      "slug": "uml_for_lld",
      "summary": "Choose class, sequence, activity, state, and use-case diagrams based on the design question being answered.",
      "group": "Modeling",
      "javaFileCount": 0,
      "entryFile": ""
    }
  ],
  "repositories": [
    {
      "id": "lld-atlas",
      "title": "LLD Atlas canonical repository",
      "commit": null,
      "branch": null,
      "remote": null,
      "localPath": ".",
      "license": "Local canonical material",
      "role": "Maintained learning notes, interview questions, patterns, principles, UML, concurrency, and Java/Python reference solutions.",
      "fileCount": 738,
      "previewableFiles": 737,
      "bytes": 1857804,
      "byKind": {
        "Notes / document": 159,
        "Source code": 576,
        "Build / configuration": 2,
        "Other tracked file": 1
      },
      "byLanguage": {
        "Markdown": 159,
        "Java": 560,
        "XML": 2,
        "File": 1,
        "Python": 16
      }
    },
    {
      "id": "awesome-low-level-design",
      "title": "awesome-low-level-design",
      "commit": "fc26e4033cad6d24f32caa8521044febbf065beb",
      "branch": "main",
      "remote": "https://github.com/ashishps1/awesome-low-level-design.git",
      "localPath": "References/awesome-low-level-design",
      "license": "GPL-3.0",
      "role": "Multi-language LLD solutions, OOP examples, diagrams, and design-pattern implementations.",
      "fileCount": 3343,
      "previewableFiles": 3279,
      "bytes": 15451576,
      "byKind": {
        "Other tracked file": 12,
        "Diagram / media": 42,
        "Source code": 2942,
        "Notes / document": 272,
        "Build / configuration": 50,
        "Generated / binary": 25
      },
      "byLanguage": {
        "File": 13,
        "PNG": 38,
        "C++": 384,
        "C/C++": 89,
        "TXT": 4,
        "C#": 642,
        "Go": 356,
        "MOD": 17,
        "Java": 787,
        "JPG": 1,
        "JavaScript": 73,
        "Python": 538,
        "Markdown": 269,
        "Rust": 9,
        "TOML": 1,
        "CSPROJ": 27,
        "JSON": 8,
        "DLL": 4,
        "PDB": 2,
        "SLN": 1,
        "PROPS": 1,
        "TARGETS": 1,
        "CACHE": 5,
        "EDITORCONFIG": 1,
        "LOG": 1,
        "XML": 1,
        "PlantUML": 3,
        "TypeScript": 67
      }
    },
    {
      "id": "low-level-design-primer",
      "title": "low-level-design-primer",
      "commit": "49fe9f2fc2fcd409e25b20e0bed8c37337d64ebd",
      "branch": "master",
      "remote": "https://github.com/prasadgujar/low-level-design-primer.git",
      "localPath": "References/low-level-design-primer",
      "license": "No license declared",
      "role": "Question prompts, external solution references, books, blogs, and learning resources.",
      "fileCount": 7,
      "previewableFiles": 7,
      "bytes": 34178,
      "byKind": {
        "Build / configuration": 1,
        "Notes / document": 6
      },
      "byLanguage": {
        "YAML": 1,
        "Markdown": 6
      }
    },
    {
      "id": "kumaransg-lld",
      "title": "kumaransg/LLD",
      "commit": "1698cc6f993a5014d4370b5e0db9f64d322e2400",
      "branch": "main",
      "remote": "https://github.com/kumaransg/LLD.git",
      "localPath": "References/kumaransg-LLD",
      "license": "No repository-wide license declared",
      "role": "A large machine-coding archive with multiple Java variations for the same interview problem.",
      "fileCount": 4171,
      "previewableFiles": 2946,
      "bytes": 19654343,
      "byKind": {
        "Generated / binary": 1457,
        "Notes / document": 68,
        "Source code": 2514,
        "Build / configuration": 59,
        "Diagram / media": 15,
        "Other tracked file": 58
      },
      "byLanguage": {
        "File": 416,
        "XML": 298,
        "IML": 39,
        "CLASS": 676,
        "KOTLIN_MODULE": 5,
        "Markdown": 54,
        "Java": 2505,
        "PDF": 5,
        "JAR": 21,
        "YAML": 4,
        "Properties": 19,
        "PNG": 8,
        "BAT": 6,
        "Gradle": 11,
        "V2": 1,
        "C#": 11,
        "JSON": 6,
        "DLL": 2,
        "EXE": 2,
        "PDB": 2,
        "CSPROJ": 1,
        "SLN": 1,
        "PROPS": 1,
        "TARGETS": 1,
        "CACHE": 6,
        "TXT": 14,
        "BIN": 4,
        "LOCK": 3,
        "PB": 6,
        "LST": 6,
        "CQL": 8,
        "JPG": 3,
        "CSV": 1,
        "HTML": 3,
        "CMD": 3,
        "SQLITE": 1,
        "ZIP": 7,
        "PREFS": 6,
        "GIF": 1,
        "JPEG": 4
      }
    }
  ]
} as const;
