from datetime import datetime
from typing import Protocol

from .domain import Booking, SeatHold, SeatInventory, Show


class BookingRepository(Protocol):
    def list_shows(self) -> tuple[Show, ...]: ...
    def get_show(self, show_id: str) -> Show | None: ...
    def get_hold(self, hold_id: str) -> SeatHold | None: ...
    def unavailable_seats(self, show_id: str, now: datetime) -> SeatInventory: ...
    def save_hold_if_available(self, hold: SeatHold, now: datetime) -> bool: ...
    def save_booking_if_hold_active(self, booking: Booking, now: datetime) -> bool: ...
